---
{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "snappcloud-status-frontend.fullname" $ }}
spec:
  host: {{ .Values.route.host | quote }}
  port:
    targetPort: {{ $.Values.service.port }}
  to:
    kind: Service
    name: {{ include "snappcloud-status-frontend.fullname" $ }}
    weight: 100
  wildcardPolicy: None
{{- end }}
