replicaCount: 2

resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: snappcloud-status-frontend.mohammadne-playground.apps.private.okd4.teh-1.snappcloud.io
      router: private
      name: private
