replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 800m
    memory: 512Mi

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: snappcloud-status-frontend.mohammadne-playground.apps.private.okd4.teh-1.snappcloud.io
      router: private
      name: private
